# Generated by Django 4.2.1 on 2023-06-04 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scholarships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='donor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='institution_donation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='users.institution'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='scolarship_donation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='scholarships.scholarship'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.beneficiary'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.institution'),
        ),
        migrations.AddField(
            model_name='partialtransaction',
            name='donor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partialtransaction_donator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partialtransaction',
            name='institution_donation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partialtransaction_donations', to='users.institution'),
        ),
        migrations.AddField(
            model_name='partialtransaction',
            name='scolarship_donation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partialtransaction_donations', to='scholarships.scholarship'),
        ),
    ]
