# Generated by Django 4.2.1 on 2023-06-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_transaction',
            field=models.DateTimeField(),
        ),
    ]
