# Generated by Django 4.2.1 on 2023-06-03 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('payment', models.CharField(max_length=120)),
                ('type_pay', models.CharField(choices=[('PSE', 'PSE'), ('Cards', 'Card'), ('PayPal', 'PayPal')], max_length=200, null=True)),
                ('donor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partialtransaction_donator', to=settings.AUTH_USER_MODEL)),
                ('institution_donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partialtransaction_donations', to='users.institution')),
                ('scolarship_donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partialtransaction_donations', to='scholarships.scholarship')),
            ],
        ),
    ]
