# Generated by Django 4.2.1 on 2023-06-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0002_alter_transaction_date_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_transaction',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
