# Generated by Django 4.2.1 on 2023-06-04 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0002_initial'),
        ('scholarships', '0002_partialtransaction'),
    ]

    operations = [
    ]
