# Generated by Django 4.2.1 on 2023-05-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Beneficiario'), (2, 'Donante natural'), (3, 'Donante juridico'), (4, 'Institución')]),
        ),
    ]
