# Generated by Django 4.2.1 on 2023-05-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='verificationState',
            field=models.CharField(choices=[('A', 'Aprobada'), ('P', 'Pendiente'), ('R', 'Rechazada')], default='P', max_length=30),
        ),
    ]
