# Generated by Django 4.1.7 on 2023-05-12 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='type_institution',
            field=models.CharField(choices=[('Tecnica', 'Tecnica'), ('Tecnologica', 'Tecnologica'), ('Pregrado', 'Pregrado'), ('Posgrado', 'Posgrado')], max_length=255),
        ),
    ]
