# Generated by Django 4.1.7 on 2023-05-13 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_institution_type_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='type_institution',
            field=models.CharField(max_length=255),
        ),
    ]
