# Generated by Django 4.2.1 on 2023-05-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='idType',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Tarjeta de Identidad'), (2, 'Cédula de Ciudadania'), (3, 'Cédula extranjera'), (4, 'Nit')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='numID',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Beneficiary'), (2, 'Donor'), (3, 'Institution')], default=1),
            preserve_default=False,
        ),
    ]
