# Generated by Django 4.2.1 on 2023-05-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_institution_type_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Beneficiario'), (2, 'Donante natural'), (3, 'Donante juridico'), (4, 'Institución'), (5, 'Admin')]),
        ),
    ]
