# Generated by Django 4.2.1 on 2023-05-11 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_profilepicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro')], max_length=15)),
            ],
            options={
                'verbose_name': 'Beneficiary',
                'verbose_name_plural': 'Beneficiaries',
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donor',
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('type_institution', models.CharField(choices=[('Tecnicas', 'Tecnicas'), ('Tecnologas', 'Tecnologas'), ('Universitaria', 'Universitaria')], max_length=200)),
                ('location', models.CharField(max_length=70)),
                ('money_donation', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('users.user',),
        ),
        migrations.AlterField(
            model_name='user',
            name='idType',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Tarjeta de Identidad'), (2, 'Cédula de Ciudadanía'), (3, 'Cédula extranjera'), (4, 'NIT')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Beneficiario'), (2, 'Donante'), (3, 'Institución')]),
        ),
    ]
